# Generated by Django 4.2.16 on 2024-09-28 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("task", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="task", name="user",),
    ]
